### ISSUE TITLE
Free Tuning Bug

### ISSUE THREAD

**Issue by JaroSound** [ESX-Org/esx_lscustom#18]
If someone chooses the given part of tuning and then opens a different menu, for example from the billing, this part is assembled for free.

**Comment by JaroSound** [comment]
Any fix?

**Comment by nykroza** [comment]
the problem is still around, if we change one car and a new one come inside the LSCustom and just hit backspace, he will have all the modification of the last car.

**Comment by ElPumpo** [comment]
Fixed in 7ae6bbb87b34d956963e28018da685268ec99aed

**Comment by Xseba360** [comment]
Apparently you can still get free tuning when you select a modification - and leave the server (ie. quit in console, alt f4)
